T_max: 120
base_lr: 0.0003
batch_size: 8
config: "config/ASgcn/train_fold1.yaml"
debug: false
device:
- 3
early_stop_patience: null
eta_min: 1.0e-06
eval_interval: 5
feeder: feeder.feeder_kinetics.Feeder_kinetics
gamma: 0.1
ignore_weights: []
log_interval: 100
model: net.aagcn.AAGCN
model_args:
  edge_importance_weighting: true
  graph_args:
    layout: alphapose
    strategy: spatial
  in_channels: 3
  num_class: 5
  use_amputee_attention: true
  attention_weight: 2.0
  lambda_action: 0.5
nesterov: true
num_epoch: 120
num_worker: 4
optimizer: AdamW
pavi_log: false
phase: train
print_log: true
save_interval: 10
save_log: true
save_result: false
scheduler: CosineAnnealingLR
scheduler_factor: 0.3
scheduler_min_lr: 1.0e-07
scheduler_mode: min
scheduler_patience: 7
scheduler_threshold: 0.0001
scheduler_verbose: true
show_topk:
- 1
- 5
start_epoch: 0
step: []
step_size: 10
test_batch_size: 8
test_feeder_args:
  data_path: "./data/last_amputee/fold_1"
  ignore_empty_sample: true
  label_path: "./data/last_amputee/fold_1/val_label.pkl"
  num_person_in: 1
  num_person_out: 1
train_feeder_args:
  data_path: "./data/last_amputee/fold_1"
  ignore_empty_sample: true
  label_path: "./data/last_amputee/fold_1/train_label.pkl"
  num_person_in: 1
  num_person_out: 1
  random_choose: true
  random_move: true
  random_shift: true
  window_size: 300
use_class_weight: true
use_gpu: true
warmup: true
warmup_epochs: 5
warmup_start_lr: 1.0e-06
weight_decay: 0.015
weights: null
work_dir: "./work_dir/recognition/last_amputee/ASgcn_fold1"

